module GlobalData

  def self.set_duration
    duration = [{hours_string: '72 Hours', hours_int: 72},
      {hours_string: '24 Hours', hours_int: 24},
      {hours_string: '2 Hours', hours_int: 2}].sample
    timestamp = DateTime.now + duration[:hours_int]
    [timestamp, duration[:hours_string], duration[:hours_int]]
  end

  def self.choose_and_create
    duration_hash = GlobalData.set_duration
    new_census = CENSUSDATA.sample
    Census.create(
      description:  new_census[:description],
      option_01:    new_census[:option_01],
      option_02:    new_census[:option_02],
      option_03:    new_census[:option_03],
      duration:     duration_hash[1],
      end_time:     Time.now + duration_hash[2].hours,
      active:       1,
      user_id:      new_census[:user_id]
    )
  end

  def self.choose_and_create_closed
    duration_hash = GlobalData.set_duration
    new_census = CENSUSDATA.sample
    Census.create(
      description:  new_census[:description],
      option_01:    new_census[:option_01],
      option_02:    new_census[:option_02],
      option_03:    new_census[:option_03],
      duration:     duration_hash[1],
      end_time:     Time.now + duration_hash[2].hours,
      active:       0,
      user_id:      new_census[:user_id]
    )
  end

  def self.cast_opinions
    active = Census.where(active: true).sort_by{|census| census.created_at}.reverse
    active.each do |census|
      6.times do
        Opinion.create(
          user_id:    rand(1..9),
          census_id:  census.id,
          chosen_option: rand(1..3)
        )
      end
    end
  end

   CENSUSDATA = [
    { description:  "What's the best kind of chocolate?",
      option_01:    'Dark',
      option_02:    'Milk',
      option_03:    'White',
      duration:     '2 Hours',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What's the best cartoon sitcom?",
      option_01:    'Family Guy',
      option_02:    'The Simpsons',
      option_03:    'Seth Park',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best Burger?",
      option_01:    "Wendy's",
      option_02:    "McDonald's",
      option_03:    'Five Guys',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "How do you fall asleep?",
      option_01:    'Counting sheep',
      option_02:    'To a TV',
      option_03:    'In a Box with a Fox',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Would You Rather?",
      option_01:    'Take a shower with Mike Tyson',
      option_02:    'Change your name to Adolf',
      option_03:    'Never Eat Chocolate Again',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would You Rather?",
      option_01:    'No Internet',
      option_02:    'No Cell Phone',
      option_03:    'No TV',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would you rather no one show up to?",
      option_01:    'Your Baptism',
      option_02:    'Your Wedding',
      option_03:    'Your Funeral',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Would You Rather?",
      option_01:    'Go to the past',
      option_02:    'Go to the future',
      option_03:    'Stay in the present',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Would You Rather?",
      option_01:    'True love',
      option_02:    '$10,000,000',
      option_03:    'Immortality',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Who would you rather date?",
      option_01:    'The girl next door',
      option_02:    'Your favorite celebrity',
      option_03:    'An android',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which planet would you visit first?",
      option_01:    'Venus',
      option_02:    'Mars',
      option_03:    'Pluto',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which do you believe in?",
      option_01:    'Ghosts',
      option_02:    'Bigfoot',
      option_03:    'UFOs',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Would you rather?",
      option_01:    'Win the lottery',
      option_02:    'Live twice as long',
      option_03:    'Be able to fly',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would you rather be?",
      option_01:    'The smartest person',
      option_02:    'The best athlete',
      option_03:    'The hottest person',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would you rather be?",
      option_01:    'Twice your height',
      option_02:    'Double your weight',
      option_03:    'Impotent',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which should I get?",
      option_01:    'Belly button ring',
      option_02:    'Cartilage piercing',
      option_03:    'Upperback tattoo',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would you rather be?",
      option_01:    'Doctor',
      option_02:    'Lawyer',
      option_03:    'Stockbroker',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would you rather be able to do?",
      option_01:    'Rewind your life',
      option_02:    'Pause your life',
      option_03:    'Fast forward your life',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best Franchise?",
      option_01:    'Star Wars',
      option_02:    'Harry Potter',
      option_03:    'Star Trek',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best cop show ever?",
      option_01:    'The Wire',
      option_02:    'NYPD Blue',
      option_03:    'Cops',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Who was worst?",
      option_01:    'Hitler',
      option_02:    'Napoleon',
      option_03:    'Stalin',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What scares you most?",
      option_01:    'Zombie apocalypse',
      option_02:    'World War III',
      option_03:    'Alien invasion',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What would you rather fight?",
      option_01:    'Horse-sized duck',
      option_02:    'Duck-sized horse',
      option_03:    'Liger',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Would you play Russian Roulette once for $100k?",
      option_01:    'Yes',
      option_02:    'Maybe',
      option_03:    'No',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best search engine ever?",
      option_01:    'Ask Jeeves',
      option_02:    'Yahoo!',
      option_03:    'Google',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would you rather be able to do?",
      option_01:    'Speak all foreign languages',
      option_02:    'Speak to all animals',
      option_03:    'Speak to the dead',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Who kicks the most ass?",
      option_01:    'Ninjas',
      option_02:    'Wizards',
      option_03:    'Sumo Wrestlers',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would you rather?",
      option_01:    'Go deaf in one ear',
      option_02:    'Go blind in one eye',
      option_03:    'Never use the Internet again',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best Beatles Album?",
      option_01:    'Sgt. Peppers',
      option_02:    'Help!',
      option_03:    'White Album',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best Beatle?",
      option_01:    'John',
      option_02:    'Paul',
      option_03:    'George',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best British Band?",
      option_01:    'Beatles',
      option_02:    'Rolling Stones',
      option_03:    'Oasis',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best Grunge Band?",
      option_01:    'Nirvana',
      option_02:    'Pearl Jam',
      option_03:    'Soundgarden',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which Talk Show Host Was Best",
      option_01:    'Carson',
      option_02:    'Letterman',
      option_03:    'Leno',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Who would you rather meet?",
      option_01:    "Conan O'Brien",
      option_02:    'Howard Stern',
      option_03:    'Bob Saget',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best drive time radio host?",
      option_01:    'Don Imus',
      option_02:    'Howard Stern',
      option_03:    'Opie & Anthony',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which cola should I buy?",
      option_01:    'Pepsi',
      option_02:    'Coke',
      option_03:    'RC',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Most iconic guitar?",
      option_01:    'Stratocaster',
      option_02:    'Les Paul',
      option_03:    'Flying-V',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Who's got the worst hair?",
      option_01:    'Donald Trump',
      option_02:    'Rod Blagojevich',
      option_03:    'Bernie Sanders',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which standup is your favorite?",
      option_01:    'Jerry Seinfeld',
      option_02:    'Chris Rock',
      option_03:    'Louis CK',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What's your favorite operating system?",
      option_01:    'Windows',
      option_02:    'OSX',
      option_03:    'Linux',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which do you watch?",
      option_01:    'Conan',
      option_02:    'Fallon',
      option_03:    'Colbert',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which inkjet printer brand should I buy?",
      option_01:    'HP',
      option_02:    'Epson',
      option_03:    'Samsung',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which car should I buy?",
      option_01:    'Toyota Corolla',
      option_02:    'Ford Focus',
      option_03:    'Honda Civic',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best hybrid car to buy?",
      option_01:    'Ford Fusion',
      option_02:    'Toyota Prius',
      option_03:    'Lexus CT200h',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "I need a new TV, which brand to get?",
      option_01:    'Samsung',
      option_02:    'LG',
      option_03:    'Toshiba',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Where should I go on vacation?",
      option_01:    'Mexico',
      option_02:    'France',
      option_03:    'Thailand',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best Spring Break destination?",
      option_01:    'Daytona Beach, FL',
      option_02:    'Fire Island, NY',
      option_03:    'Malibu, CA',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Who had history's coolest facial hair?",
      option_01:    'Ambros Burnside',
      option_02:    'Karl Marx',
      option_03:    'Hitler',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which game show can't you live without?",
      option_01:    'Jeopardy!',
      option_02:    'Family Feud',
      option_03:    'Wheel of Fortune',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best guitarist of all time?",
      option_01:    'Jimi Hendrix',
      option_02:    'Eric Clapton',
      option_03:    'Chet Atkins',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which dog is the ugliest?",
      option_01:    'Boston Terrier',
      option_02:    'Schnauzer',
      option_03:    'Pug',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "In how many years can you master a new language?",
      option_01:    '1',
      option_02:    '2',
      option_03:    '3+',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What's cuter?",
      option_01:    'Kuala Bear',
      option_02:    'Baby Panda',
      option_03:    'Daniel Radcliffe',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Most important founding father?",
      option_01:    'Washington',
      option_02:    'Franklin',
      option_03:    'Jefferson',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which human invention was most important?",
      option_01:    'The Wheel',
      option_02:    'The Steam Engine',
      option_03:    'The Internet',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Who would you most like to meet?",
      option_01:    'Anderson Cooper',
      option_02:    'Wolf Blitzer',
      option_03:    'Kelly Ripa',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "History's best president?",
      option_01:    'Washington',
      option_02:    'Lincoln',
      option_03:    'FDR',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What job would you rather have?",
      option_01:    'President of France',
      option_02:    'CEO of Haliburton',
      option_03:    'Bassist for Nickelback',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which size bed do you sleep in?",
      option_01:    'Twin',
      option_02:    'Queen',
      option_03:    'King',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "My fridge died, which brand should I replace it with?",
      option_01:    'GE',
      option_02:    'Whirlpool',
      option_03:    'Frigidaire',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "With one wish, I'd for for:",
      option_01:    'World Peace',
      option_02:    'Your own immortality',
      option_03:    '1 billion dollars',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Coolest cinema hero?",
      option_01:    'James Bond',
      option_02:    'Jason Borne',
      option_03:    'Rambo',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which is the best game show host?",
      option_01:    'Alex Trebek',
      option_02:    'Pat Sajak',
      option_03:    'Steve Harvey',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Most iconic Mac of all time?",
      option_01:    'Apple II',
      option_02:    'Macintosh',
      option_03:    'iMac',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which laptop is most durable?",
      option_01:    'Macbook Pro',
      option_02:    'Lenovo Ideapad',
      option_03:    'Dell XPS 13',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which did you play most?",
      option_01:    'Super Mario',
      option_02:    'Donkey Kong Country',
      option_03:    'Super Smash Bros',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best Nintendo console of all time?",
      option_01:    'Super Nintendo',
      option_02:    'Nintendo 64',
      option_03:    'Wii',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which game console to buy?",
      option_01:    'PS4',
      option_02:    'Xbox One',
      option_03:    'Wii U',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What's you're favorite handheld for games?",
      option_01:    'PSP',
      option_02:    'Nintendo DS',
      option_03:    'Gameboy Color',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which department store has the best bargains?",
      option_01:    'Kohls',
      option_02:    'Macys',
      option_03:    'Sears',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Where do you grocery shop?",
      option_01:    'Shaws',
      option_02:    'Price Chopper',
      option_03:    'Stop & Shop',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which school do you wish you had a degree from?",
      option_01:    'Harvard',
      option_02:    'Yale',
      option_03:    'Oxford',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Should I get a hedgehog?",
      option_01:    'Yes',
      option_02:    'Maybe',
      option_03:    'No',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "In Pokemon Red, which one should I choose?",
      option_01:    'Bulbasaur',
      option_02:    'Charazard',
      option_03:    'Squirtle',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Should I enroll in a coding bootcamp",
      option_01:    'Yes',
      option_02:    'Maybe',
      option_03:    'No',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What color car should I get?",
      option_01:    'White',
      option_02:    'Black',
      option_03:    'Grey',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What's your favorite drinking song?",
      option_01:    '1 Burbon, 1 Scotch, 1 Beer',
      option_02:    'Gin & Juice',
      option_03:    'Alcohol (Brad Paisley)',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Dopest Eminem Rhymes?",
      option_01:    'My Name Is',
      option_02:    'Till I Collapse',
      option_03:    'Without Me',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Best Drinking Game?",
      option_01:    'President',
      option_02:    'Flip Cup',
      option_03:    'Beer Pong',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Worst solo instrument?",
      option_01:    'Kazoo',
      option_02:    'Bassoon',
      option_03:    'French Horn',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Who was the most talent in NWA?",
      option_01:    'Eazy-E',
      option_02:    'Ice Cube',
      option_03:    'Dr. Dre',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Greatest American Songsmith?",
      option_01:    'Woody Guthrie',
      option_02:    'Bob Dylan',
      option_03:    'Bruce Springsteen',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which type of clock do you prefer?",
      option_01:    'Digital',
      option_02:    'Analog',
      option_03:    'Sundial',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which coding language is most powerful?",
      option_01:    'C++',
      option_02:    'Ruby',
      option_03:    'Go',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which programming language should I learn first?",
      option_01:    'Ruby',
      option_02:    'Python',
      option_03:    'Java',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What's the most difficult front-end language?",
      option_01:    'JavaScript',
      option_02:    'HTML',
      option_03:    'CSS',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Where would you rather live?",
      option_01:    'China',
      option_02:    'Russia',
      option_03:    'South Korea',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which sport is best for losing weight?",
      option_01:    'Basketball',
      option_02:    'Tennis',
      option_03:    'Swimming',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What sport do you watch most?",
      option_01:    'Football',
      option_02:    'Baseball',
      option_03:    'Basketball',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which team?",
      option_01:    'Red Sox',
      option_02:    'Yankees',
      option_03:    'Cubs',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Most influential standup comic?",
      option_01:    'Lenny Bruce',
      option_02:    'George Carlin',
      option_03:    'Bill Cosby',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which war would you least want to fight in?",
      option_01:    'American Revolution',
      option_02:    'American Civil',
      option_03:    'World War 2',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which sitcom did you watch the most in the 90s?",
      option_01:    'Seinfeld',
      option_02:    'Friends',
      option_03:    'Drew Carey',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which type of guitar sounds better to you?",
      option_01:    'Acoustic',
      option_02:    'Electric',
      option_03:    'Cigar Box',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which Star Wars should I watch?",
      option_01:    'A New Hope',
      option_02:    'Empire Strikes Back',
      option_03:    'Return of the Jedi',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "What's the best arcade game ever?",
      option_01:    'Pacman',
      option_02:    'Donkey Kong',
      option_03:    'Tetris',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which crime movie to watch tomorrow?",
      option_01:    'The Godfather',
      option_02:    'Scarface',
      option_03:    'Seven',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which comedy made you laugh the hardest?",
      option_01:    'Animal House',
      option_02:    'Caddyshack',
      option_03:    'Groundhog Day',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which would you want as a pet?",
      option_01:    'Elephant',
      option_02:    'Giraffe',
      option_03:    'Tank full of jellyfish',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
    { description:  "Which website do visit most?",
      option_01:    'Facebook',
      option_02:    'Twitter',
      option_03:    'Instagram',
      end_time:     GlobalData.set_duration,
      active:       true,
      user_id:      rand(1..9) },
  ].freeze

end
